name: noteapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  objectbox: 4.0.2 # Add the latest version available if different
  objectbox_flutter_libs: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.2.2
  objectbox_generator: any

flutter:
  uses-material-design: true